name: Elite Builds OnDemand
on:
  workflow_dispatch:
    inputs:
      eliteConfigName:
        description: 'Elite Config Name'
        required: true

env:
  auth: ${{ secrets.auth }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  DISPLAY_RESPONSE: ${{ secrets.DISPLAY_RESPONSE }}
  REPO: ${{ github.event.repository.name }}
  OWNER: ${{ github.event.repository.owner.login }}
  SF_PWD: ${{ secrets.SF_PWD }}
  RELEASE_TYPE: 'stable'
  ENVIRONMENT_TYPE: ${{ secrets.ENVIRONMENT_TYPE }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.4.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Setup SSH Keys and known_hosts using kielabokkie
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            ssh-host: frs.sourceforge.net
      
      - name: Environment Details and clean up
        run: |
          rm -rf Build 10 11 12 Releases canary-release release nikgapps.github.io TempPackages
          echo "repo: $REPO"
          echo "repo owner: $OWNER"
      
      - name: Checking Java Version
        run: java -version
      
      - name: Initialization and Fetching the Source Code
        run: |
           git config --global user.name "$USER_NAME"
           git config --global user.email "$EMAIL"
           git config --global http.postBuffer 1048576000
           git clone --depth=1 git@github.com:nikgapps/ondemand.git
           
      - name: Installing Requirements
        run: |
           python3 -m pip install wheel setuptools testresources
           cd ondemand
           pip3 install -r requirements.txt
           cd ..

      - name: Building Custom Builds
        run: |
           cd ondemand
           python3 main.py -A 10,11,12,12.1,13 -U -E ${{ github.event.inputs.eliteConfigName }}
           cd ..
     
      - name: Updating download count
        run: |
           cd ondemand
           python3 analytics_control.py
           cd ..
