name: Test Deployment

on:
  workflow_dispatch:

env:
  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  REPOSITORY: ${{ secrets.REPOSITORY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  SOURCE: ${{ secrets.SOURCE }}
  SF_PWD: ${{ secrets.SF_PWD }}
  RELEASE_TYPE: 'stable'
  ENVIRONMENT_TYPE: ${{ secrets.ENVIRONMENT_TYPE }}
  PACKAGE_LIST: core

jobs:
  build:
    runs-on: macos-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Setup SSH Keys and known_hosts for github
         uses: webfactory/ssh-agent@v0.4.1
         with:
             ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
             
#        - name: Setup SSH Keys for gitlab.com
#          uses: kielabokkie/ssh-key-and-known-hosts-action@v1
#          with:
#              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#              ssh-host: gitlab.com
       
       - name: Setup SSH Keys for sourceforge.net
         uses: kielabokkie/ssh-key-and-known-hosts-action@v1
         with:
             ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
             ssh-host: frs.sourceforge.net
            
       - name: Installing Requirements
         run: |
            python3 -m pip install wheel setuptools testresources
        
       - name: Setup Git Repository
         run: |
            git clone git@github.com:nikgapps/project.git
            cd project
            pip3 install -r requirements.txt
            cd ..
#            git clone git@github.com:nikgapps/updater.git
#            cd updater
#            pip3 install -r requirements.txt
#            cd ..
            
       - name: Update Git configs
         run: |
            git config --global user.name "$USER_NAME"
            git config --global user.email "$EMAIL"
            git config --global http.postBuffer 157286400

#        - name: Syncing OEM updates and extract overlays
#          run: |
#             cd updater
#             python3 main.py
#             python3 overlays.py
#             cd ..
       
       - name: Running test
         run: |
            cd project
            python3 test.py
            cd ..
       
       
