name: CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Android SDK
      run: |
        brew install --cask adoptopenjdk/openjdk/adoptopenjdk8
        brew install gradle
        wget -O sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip
        unzip sdk-tools.zip -d $HOME/Library/Android/sdk
        echo "export ANDROID_HOME=$HOME/Library/Android/sdk" >> $HOME/.bash_profile
        echo "export PATH=$PATH:$ANDROID_HOME/tools/bin" >> $HOME/.bash_profile
        echo "export PATH=$PATH:$ANDROID_HOME/platform-tools" >> $HOME/.bash_profile
        source $HOME/.bash_profile
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        
    - name: Verify zipalign installation
      run: |
        echo "Verifying zipalign installation..."
        zipalign
